#!/bin/sh

rm -r 0.*
rm log.*
rm *.dat
rm post/*.*
rm log

rm -r pascal/0.0*
rm    pascal/log.*
rm    pascal/plot_*.eps
cd pascal 
rm -r 0.* 1* 2* 3* 4* 5* 6* 7* 8* 9*
rm numerical_compare_convective_cooling_1000.dat
rm numerical_compare_convective_cooling_800.dat
rm numerical_solution_bc_convective_cooling_1000.dat
rm numerical_solution_bc_convective_cooling_800.dat

rm numerical_solution_BC_convetive_cooling_1000
rm numerical_solution_BC_convetive_cooling_800

rm plot.eps
